package com.taoswork.tallybook.general.authority.core.resource;

import java.util.Collection;

/**
 * .AccessibleAreas describes accessible information for
 *      a particular user (type: IPermissionAuthority)
 *      with particular access (type: Access)
 *
 *  Generated by: IAccessVerifier
 *  Consumed by: filter query
 *
 *  Usage:
 *  inUnionMode, default: false;
 *  If not union mode:
 *      in pipe-like:
 *          all | or(passFilters) | drop or(blockFilters)
 *      in sql-like:
 *          select * where m1 true or m2 true or ... or mx true and not (nm1 true or nm2 true or ...)
 *          select * where m1 true or m2 true or ... or mx true and nm1 false and nm2 false and ...
 *  If union mode
 *      in pipe-like:
 *          (all | or(passFilters)) and (alL | drop or(blockFilters))
 *      in sql-like:
 *          select * where m1 true or m2 true or not (nm1 true or nm2 true)
 *          select * where m1 true or m2 true or (nm1 false and nm2 false)
 */
public final class AccessibleAreas {
    public final boolean inUnionMode;
    public final Collection<String> passFilters;
    public final Collection<String> blockFilters;

    public AccessibleAreas(
        Collection<String> passFilters,
        Collection<String> blockFilters) {
        this(passFilters, blockFilters, false);
    }

    public AccessibleAreas(
        Collection<String> passFilters,
        Collection<String> blockFilters, boolean inUnionMode) {
        this.passFilters = passFilters;
        this.blockFilters = blockFilters;
        this.inUnionMode = inUnionMode;
    }
}
