package com.taoswork.tallybook.general.authority.core.resource;

import com.taoswork.tallybook.general.authority.core.basic.ProtectionMode;

import java.util.Collection;

/**
 * For a specified resource instance, for its belonging IResourceProtection,
 * The instance could be included in a set of filters,
 * and also not included by the left filters
 *
 * Generated by
 *      IResourceProtectionManager ({@link com.taoswork.tallybook.general.authority.core.resource.IResourceProtectionManager})
 * Consumed by
 *      AccessVerifier ({@link com.taoswork.tallybook.general.authority.core.verifier.impl.AccessVerifier})
 */
public final class ResourceFitting {

    public final boolean isMasterControlled;
    public final ProtectionMode protectionMode;

    public final Collection<String> matchingFilters;
    public final Collection<String> unmatchedFilters;

    public ResourceFitting(boolean isMasterControlled,
                           ProtectionMode protectionMode,
                           Collection<String> matchingFilters,
                           Collection<String> unmatchedFilters) {
        this.isMasterControlled = isMasterControlled;
        this.protectionMode = protectionMode;
        this.matchingFilters = matchingFilters;
        this.unmatchedFilters = unmatchedFilters;
    }
}
